// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['gui']['App']['ClearLogs']();
}

export function CloseWindow() {
  return window['go']['gui']['App']['CloseWindow']();
}

export function DebugStatus() {
  return window['go']['gui']['App']['DebugStatus']();
}

export function LoadConfig() {
  return window['go']['gui']['App']['LoadConfig']();
}

export function Logs() {
  return window['go']['gui']['App']['Logs']();
}

export function MatchTestStatus() {
  return window['go']['gui']['App']['MatchTestStatus']();
}

export function MinimizeWindow() {
  return window['go']['gui']['App']['MinimizeWindow']();
}

export function Restart() {
  return window['go']['gui']['App']['Restart']();
}

export function SaveConfig(arg1) {
  return window['go']['gui']['App']['SaveConfig'](arg1);
}

export function SelectMatchTestImage() {
  return window['go']['gui']['App']['SelectMatchTestImage']();
}

export function SelectWorldMapFile() {
  return window['go']['gui']['App']['SelectWorldMapFile']();
}

export function SetInspectWindow(arg1) {
  return window['go']['gui']['App']['SetInspectWindow'](arg1);
}

export function Start() {
  return window['go']['gui']['App']['Start']();
}

export function StartMapMatchTest(arg1, arg2) {
  return window['go']['gui']['App']['StartMapMatchTest'](arg1, arg2);
}

export function Status() {
  return window['go']['gui']['App']['Status']();
}

export function Stop() {
  return window['go']['gui']['App']['Stop']();
}

export function StopMapMatchTest() {
  return window['go']['gui']['App']['StopMapMatchTest']();
}
