// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';
import {appconfig} from '../models';

export function ClearLogs():Promise<void>;

export function CloseWindow():Promise<void>;

export function DebugStatus():Promise<gui.DebugStatus>;

export function LoadConfig():Promise<appconfig.Config>;

export function Logs():Promise<Array<string>>;

export function MatchTestStatus():Promise<gui.MatchTestStatus>;

export function MinimizeWindow():Promise<void>;

export function Restart():Promise<gui.Status>;

export function SaveConfig(arg1:appconfig.Config):Promise<void>;

export function SelectMatchTestImage():Promise<string>;

export function SelectWorldMapFile():Promise<string>;

export function SetInspectWindow(arg1:boolean):Promise<gui.DebugStatus>;

export function Start():Promise<gui.Status>;

export function StartMapMatchTest(arg1:string,arg2:number):Promise<gui.MatchTestStatus>;

export function Status():Promise<gui.Status>;

export function Stop():Promise<gui.Status>;

export function StopMapMatchTest():Promise<gui.MatchTestStatus>;
